//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NamesResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abbasali_Moghadam {
            get {
                return ResourceManager.GetString("Abbasali_Moghadam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abbas_Ghiasi {
            get {
                return ResourceManager.GetString("Abbas_Ghiasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abbas_Sedighinezhad {
            get {
                return ResourceManager.GetString("Abbas_Sedighinezhad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abdollah_PanahiPoor {
            get {
                return ResourceManager.GetString("Abdollah_PanahiPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abdolreza_Abdi {
            get {
                return ResourceManager.GetString("Abdolreza_Abdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abdol_Rasoul_AnvariPoor {
            get {
                return ResourceManager.GetString("Abdol_Rasoul_AnvariPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Abodl_Hamid_Zokaie {
            get {
                return ResourceManager.GetString("Abodl_Hamid_Zokaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Afshin_Froutan {
            get {
                return ResourceManager.GetString("Afshin_Froutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Afshin_GholiPour_Baradari {
            get {
                return ResourceManager.GetString("Afshin_GholiPour_Baradari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Afshin_Hassanzadeh {
            get {
                return ResourceManager.GetString("Afshin_Hassanzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Afshin_Yousefi {
            get {
                return ResourceManager.GetString("Afshin_Yousefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahamad_Yousefzadeh {
            get {
                return ResourceManager.GetString("Ahamad_Yousefzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahamd_Kashkouli {
            get {
                return ResourceManager.GetString("Ahamd_Kashkouli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmad_Bahrami {
            get {
                return ResourceManager.GetString("Ahmad_Bahrami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmad_Ebadi {
            get {
                return ResourceManager.GetString("Ahmad_Ebadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ahmad_Rastegharian {
            get {
                return ResourceManager.GetString("Ahmad_Rastegharian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aliakbar_Moieni {
            get {
                return ResourceManager.GetString("Aliakbar_Moieni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aliasghar_Zafarasoudeh {
            get {
                return ResourceManager.GetString("Aliasghar_Zafarasoudeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Alireza_Jahangiri {
            get {
                return ResourceManager.GetString("Alireza_Jahangiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Alireza_jalalifarahni {
            get {
                return ResourceManager.GetString("Alireza_jalalifarahni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Alireza_Karami {
            get {
                return ResourceManager.GetString("Alireza_Karami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Alireza_Karimzadhagh {
            get {
                return ResourceManager.GetString("Alireza_Karimzadhagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Alireza_Mahouri {
            get {
                return ResourceManager.GetString("Alireza_Mahouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Dabagh {
            get {
                return ResourceManager.GetString("Ali_Dabagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Hemmat {
            get {
                return ResourceManager.GetString("Ali_Hemmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_jabari {
            get {
                return ResourceManager.GetString("Ali_jabari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Karami {
            get {
                return ResourceManager.GetString("Ali_Karami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Khalili {
            get {
                return ResourceManager.GetString("Ali_Khalili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Mirmansouri {
            get {
                return ResourceManager.GetString("Ali_Mirmansouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Mohammadzadeh_Jodiyani {
            get {
                return ResourceManager.GetString("Ali_Mohammadzadeh_Jodiyani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Rezaie_Mohghadam {
            get {
                return ResourceManager.GetString("Ali_Rezaie_Mohghadam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Sadeghi {
            get {
                return ResourceManager.GetString("Ali_Sadeghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ali_Shahabasi {
            get {
                return ResourceManager.GetString("Ali_Shahabasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Amirabbas_Kianfar {
            get {
                return ResourceManager.GetString("Amirabbas_Kianfar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Amjad_Kiani {
            get {
                return ResourceManager.GetString("Amjad_Kiani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Arash_Hatefi {
            get {
                return ResourceManager.GetString("Arash_Hatefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aria_Solymani {
            get {
                return ResourceManager.GetString("Aria_Solymani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Asghar_Mohammadi {
            get {
                return ResourceManager.GetString("Asghar_Mohammadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Avaz_Heydarpour {
            get {
                return ResourceManager.GetString("Avaz_Heydarpour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bahman_NaghiPour_Basmaj {
            get {
                return ResourceManager.GetString("Bahman_NaghiPour_Basmaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Behrang_Nouralishahi {
            get {
                return ResourceManager.GetString("Behrang_Nouralishahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Behzad_Azmin {
            get {
                return ResourceManager.GetString("Behzad_Azmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Behzad_Maghsoudi {
            get {
                return ResourceManager.GetString("Behzad_Maghsoudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Davood_Zeyghami {
            get {
                return ResourceManager.GetString("Davood_Zeyghami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ebrahim_Hassani {
            get {
                return ResourceManager.GetString("Ebrahim_Hassani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Elahe_Allahyari {
            get {
                return ResourceManager.GetString("Elahe_Allahyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string eysa_Bilehjani {
            get {
                return ResourceManager.GetString("eysa_Bilehjani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Farshad_jalalmanesh {
            get {
                return ResourceManager.GetString("Farshad_jalalmanesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Farshid_Frahbakhsh {
            get {
                return ResourceManager.GetString("Farshid_Frahbakhsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Farshid_Ravanshadi {
            get {
                return ResourceManager.GetString("Farshid_Ravanshadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Farzad_Fazeli {
            get {
                return ResourceManager.GetString("Farzad_Fazeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Farzin_Broumandan {
            get {
                return ResourceManager.GetString("Farzin_Broumandan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Fatemeh_Bayat {
            get {
                return ResourceManager.GetString("Fatemeh_Bayat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Fatemeh_HadiPourzadeh {
            get {
                return ResourceManager.GetString("Fatemeh_HadiPourzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Fatemeh_Javaher_Fouroshzadeh {
            get {
                return ResourceManager.GetString("Fatemeh_Javaher_Fouroshzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ferydoun_Farivar {
            get {
                return ResourceManager.GetString("Ferydoun_Farivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Foruzan_Yazdanian {
            get {
                return ResourceManager.GetString("Foruzan_Yazdanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ghasem_Soltani {
            get {
                return ResourceManager.GetString("Ghasem_Soltani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Gholamreza_Masoumi {
            get {
                return ResourceManager.GetString("Gholamreza_Masoumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GholamReza_Moradi {
            get {
                return ResourceManager.GetString("GholamReza_Moradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GholamReza_Najafi {
            get {
                return ResourceManager.GetString("GholamReza_Najafi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Habibollah_Hosseini {
            get {
                return ResourceManager.GetString("Habibollah_Hosseini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HamidReza_Jalili {
            get {
                return ResourceManager.GetString("HamidReza_Jalili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hamid_Kamalipour {
            get {
                return ResourceManager.GetString("Hamid_Kamalipour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hashem_Jarineshin {
            get {
                return ResourceManager.GetString("Hashem_Jarineshin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hassan_Soltaninia {
            get {
                return ResourceManager.GetString("Hassan_Soltaninia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hassan_Teymouri {
            get {
                return ResourceManager.GetString("Hassan_Teymouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Haydeh_Moien {
            get {
                return ResourceManager.GetString("Haydeh_Moien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hedayatollah_Elyasi {
            get {
                return ResourceManager.GetString("Hedayatollah_Elyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hedayat_Akhlagh {
            get {
                return ResourceManager.GetString("Hedayat_Akhlagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hossienali_jelvehmoghadam {
            get {
                return ResourceManager.GetString("Hossienali_jelvehmoghadam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hossien_Naddafnia {
            get {
                return ResourceManager.GetString("Hossien_Naddafnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hossien_Telavat {
            get {
                return ResourceManager.GetString("Hossien_Telavat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Houshang_Nadianmehr {
            get {
                return ResourceManager.GetString("Houshang_Nadianmehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Houshang_Shahriarye {
            get {
                return ResourceManager.GetString("Houshang_Shahriarye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Iman_Ghandi {
            get {
                return ResourceManager.GetString("Iman_Ghandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Iraj_Ghorbandaiepour {
            get {
                return ResourceManager.GetString("Iraj_Ghorbandaiepour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Jalal_Saem {
            get {
                return ResourceManager.GetString("Jalal_Saem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Javad_Sadrizadeh {
            get {
                return ResourceManager.GetString("Javad_Sadrizadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kamalodin_tabatbaie {
            get {
                return ResourceManager.GetString("Kamalodin_tabatbaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kamal_Fani {
            get {
                return ResourceManager.GetString("Kamal_Fani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kambiz_Mousavi {
            get {
                return ResourceManager.GetString("Kambiz_Mousavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kambiz_Zohouri {
            get {
                return ResourceManager.GetString("Kambiz_Zohouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kianoush_Saberi {
            get {
                return ResourceManager.GetString("Kianoush_Saberi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kobra_Ghazisaiedi {
            get {
                return ResourceManager.GetString("Kobra_Ghazisaiedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kourosh_Ghorbaninzhad {
            get {
                return ResourceManager.GetString("Kourosh_Ghorbaninzhad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Kourosh_Tiregarefakheri {
            get {
                return ResourceManager.GetString("Kourosh_Tiregarefakheri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mahmoud_Gholam_ale_mohammad {
            get {
                return ResourceManager.GetString("Mahmoud_Gholam_ale_mohammad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Basirat {
            get {
                return ResourceManager.GetString("Majid_Basirat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Dashti {
            get {
                return ResourceManager.GetString("Majid_Dashti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Ghodsi {
            get {
                return ResourceManager.GetString("Majid_Ghodsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Kabiri {
            get {
                return ResourceManager.GetString("Majid_Kabiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Khosroheydari {
            get {
                return ResourceManager.GetString("Majid_Khosroheydari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Majid_Nekoufard {
            get {
                return ResourceManager.GetString("Majid_Nekoufard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Manizhe_Yousefi {
            get {
                return ResourceManager.GetString("Manizhe_Yousefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mansour_Soltanzadeh {
            get {
                return ResourceManager.GetString("Mansour_Soltanzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Maryam_Soltanahmadi {
            get {
                return ResourceManager.GetString("Maryam_Soltanahmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Masoud_Ebrahimi {
            get {
                return ResourceManager.GetString("Masoud_Ebrahimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Masoud_Ghorbanlou {
            get {
                return ResourceManager.GetString("Masoud_Ghorbanlou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Masoud_Razaghi {
            get {
                return ResourceManager.GetString("Masoud_Razaghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Masoud_Tarbiat {
            get {
                return ResourceManager.GetString("Masoud_Tarbiat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Maziar_Falahat {
            get {
                return ResourceManager.GetString("Maziar_Falahat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Maziyar_Mahboubi {
            get {
                return ResourceManager.GetString("Maziyar_Mahboubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Dehghani_Firouzabadi {
            get {
                return ResourceManager.GetString("Mehdi_Dehghani_Firouzabadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Fathi {
            get {
                return ResourceManager.GetString("Mehdi_Fathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Heydari {
            get {
                return ResourceManager.GetString("Mehdi_Heydari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Khazaie {
            get {
                return ResourceManager.GetString("Mehdi_Khazaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Najafi {
            get {
                return ResourceManager.GetString("Mehdi_Najafi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Rahaab {
            get {
                return ResourceManager.GetString("Mehdi_Rahaab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehdi_Solymani {
            get {
                return ResourceManager.GetString("Mehdi_Solymani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehraien {
            get {
                return ResourceManager.GetString("Mehraien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehran_Kouchak {
            get {
                return ResourceManager.GetString("Mehran_Kouchak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehrdad_Mesbah_Kiaie {
            get {
                return ResourceManager.GetString("Mehrdad_Mesbah_Kiaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehrdad_Mokarram_Dorri {
            get {
                return ResourceManager.GetString("Mehrdad_Mokarram_Dorri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mehrzad_Kaviani {
            get {
                return ResourceManager.GetString("Mehrzad_Kaviani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mirmousa_Mirinezhad {
            get {
                return ResourceManager.GetString("Mirmousa_Mirinezhad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mitra_Azarasa {
            get {
                return ResourceManager.GetString("Mitra_Azarasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mitra_Gol_Mohammadie {
            get {
                return ResourceManager.GetString("Mitra_Gol_Mohammadie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadBaghar_Khosravi {
            get {
                return ResourceManager.GetString("MohammadBaghar_Khosravi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadHassan_Pourdargah {
            get {
                return ResourceManager.GetString("MohammadHassan_Pourdargah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammadhossien_Bakhshaie {
            get {
                return ResourceManager.GetString("Mohammadhossien_Bakhshaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammadjavad_Ahmadi {
            get {
                return ResourceManager.GetString("Mohammadjavad_Ahmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammadjavad_Emaieli {
            get {
                return ResourceManager.GetString("Mohammadjavad_Emaieli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammadjavad_Mehrabanian {
            get {
                return ResourceManager.GetString("Mohammadjavad_Mehrabanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_Amouzegar_Zavareh {
            get {
                return ResourceManager.GetString("MohammadReza_Amouzegar_Zavareh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_Habibi {
            get {
                return ResourceManager.GetString("MohammadReza_Habibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_Jamshidi {
            get {
                return ResourceManager.GetString("MohammadReza_Jamshidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_MohammadReza_Samdani {
            get {
                return ResourceManager.GetString("MohammadReza_MohammadReza_Samdani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_Nourozi {
            get {
                return ResourceManager.GetString("MohammadReza_Nourozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadReza_Tashakor {
            get {
                return ResourceManager.GetString("MohammadReza_Tashakor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MohammadRezvan_Nobahar {
            get {
                return ResourceManager.GetString("MohammadRezvan_Nobahar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammadtaghi_Moienvaziri {
            get {
                return ResourceManager.GetString("Mohammadtaghi_Moienvaziri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Ali_Azemati {
            get {
                return ResourceManager.GetString("Mohammad_Ali_Azemati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Forouzesh {
            get {
                return ResourceManager.GetString("Mohammad_Forouzesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Ghafari_Pour {
            get {
                return ResourceManager.GetString("Mohammad_Ghafari_Pour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Hassan_Abdollahi {
            get {
                return ResourceManager.GetString("Mohammad_Hassan_Abdollahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Hossien_Nikooiean {
            get {
                return ResourceManager.GetString("Mohammad_Hossien_Nikooiean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Piryaie {
            get {
                return ResourceManager.GetString("Mohammad_Piryaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Safdari {
            get {
                return ResourceManager.GetString("Mohammad_Safdari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Shirvani {
            get {
                return ResourceManager.GetString("Mohammad_Shirvani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_TavakoliRad {
            get {
                return ResourceManager.GetString("Mohammad_TavakoliRad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohammad_Zokaie_Ashtiani {
            get {
                return ResourceManager.GetString("Mohammad_Zokaie_Ashtiani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohsen_Zarehsharifi {
            get {
                return ResourceManager.GetString("Mohsen_Zarehsharifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mohsen_Ziyaiefard {
            get {
                return ResourceManager.GetString("Mohsen_Ziyaiefard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mojtaba_Mansouri {
            get {
                return ResourceManager.GetString("Mojtaba_Mansouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mojtaba_Marashie {
            get {
                return ResourceManager.GetString("Mojtaba_Marashie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mojtaba_Niazi {
            get {
                return ResourceManager.GetString("Mojtaba_Niazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Morteza_jabarimoghadm {
            get {
                return ResourceManager.GetString("Morteza_jabarimoghadm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Morteza_Managheb {
            get {
                return ResourceManager.GetString("Morteza_Managheb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mostafa_Kazerouni {
            get {
                return ResourceManager.GetString("Mostafa_Kazerouni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mostafa_Sadeghi {
            get {
                return ResourceManager.GetString("Mostafa_Sadeghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mousa_Shirmohammadi {
            get {
                return ResourceManager.GetString("Mousa_Shirmohammadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nader_NaderPour {
            get {
                return ResourceManager.GetString("Nader_NaderPour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nadia_Banihashem {
            get {
                return ResourceManager.GetString("Nadia_Banihashem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nahid_Naseh {
            get {
                return ResourceManager.GetString("Nahid_Naseh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nahid_Oghdaie {
            get {
                return ResourceManager.GetString("Nahid_Oghdaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nahid_Zirak {
            get {
                return ResourceManager.GetString("Nahid_Zirak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Narges_Payani {
            get {
                return ResourceManager.GetString("Narges_Payani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Naser_Parviter {
            get {
                return ResourceManager.GetString("Naser_Parviter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Omid_Aghadavoodi {
            get {
                return ResourceManager.GetString("Omid_Aghadavoodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ramak_PoshtPanah {
            get {
                return ResourceManager.GetString("Ramak_PoshtPanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rasoul_Azarfarin {
            get {
                return ResourceManager.GetString("Rasoul_Azarfarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rasoul_Farasatkish {
            get {
                return ResourceManager.GetString("Rasoul_Farasatkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reza_Farzadi {
            get {
                return ResourceManager.GetString("Reza_Farzadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reza_Jouybar {
            get {
                return ResourceManager.GetString("Reza_Jouybar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reza_KhajehNouri {
            get {
                return ResourceManager.GetString("Reza_KhajehNouri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reza_RoshanPour {
            get {
                return ResourceManager.GetString("Reza_RoshanPour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reza_TarjemanPorshokouh {
            get {
                return ResourceManager.GetString("Reza_TarjemanPorshokouh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sahereh_Saiedi {
            get {
                return ResourceManager.GetString("Sahereh_Saiedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaiedReza_Nami {
            get {
                return ResourceManager.GetString("SaiedReza_Nami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Saied_Kashani {
            get {
                return ResourceManager.GetString("Saied_Kashani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Saied_Khademi {
            get {
                return ResourceManager.GetString("Saied_Khademi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sara_Jarirahmadi {
            get {
                return ResourceManager.GetString("Sara_Jarirahmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sedighye_Ahmadi {
            get {
                return ResourceManager.GetString("Sedighye_Ahmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_AhmadReza_Salimbahrami {
            get {
                return ResourceManager.GetString("Seyed_AhmadReza_Salimbahrami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Ahmad_Rakeie {
            get {
                return ResourceManager.GetString("Seyed_Ahmad_Rakeie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Akbar_RajaieRamshe {
            get {
                return ResourceManager.GetString("Seyed_Akbar_RajaieRamshe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Ali_Emami {
            get {
                return ResourceManager.GetString("Seyed_Ali_Emami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Ebrahim_Sadeghi {
            get {
                return ResourceManager.GetString("Seyed_Ebrahim_Sadeghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Hassan_Attarzadeh {
            get {
                return ResourceManager.GetString("Seyed_Hassan_Attarzadeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Hossein_Moshtaghioun {
            get {
                return ResourceManager.GetString("Seyed_Hossein_Moshtaghioun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Hossien_Hamidi {
            get {
                return ResourceManager.GetString("Seyed_Hossien_Hamidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mansour_Fatemie {
            get {
                return ResourceManager.GetString("Seyed_Mansour_Fatemie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Masoud_Lahsaie {
            get {
                return ResourceManager.GetString("Seyed_Masoud_Lahsaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mehran_Ghoryeshi {
            get {
                return ResourceManager.GetString("Seyed_Mehran_Ghoryeshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mehrdad_Hashemi {
            get {
                return ResourceManager.GetString("Seyed_Mehrdad_Hashemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mohammad_Hashemi_Ievari {
            get {
                return ResourceManager.GetString("Seyed_Mohammad_Hashemi_Ievari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mojtaba_Karimi {
            get {
                return ResourceManager.GetString("Seyed_Mojtaba_Karimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Mostafa_Alavi {
            get {
                return ResourceManager.GetString("Seyed_Mostafa_Alavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Motahr_Shojaie {
            get {
                return ResourceManager.GetString("Seyed_Motahr_Shojaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Saied_Ghiasi {
            get {
                return ResourceManager.GetString("Seyed_Saied_Ghiasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Seyed_Saied_Jahanbakhsh {
            get {
                return ResourceManager.GetString("Seyed_Saied_Jahanbakhsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shahrbanoo_Shahbazi {
            get {
                return ResourceManager.GetString("Shahrbanoo_Shahbazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shahrokh_Havaejie {
            get {
                return ResourceManager.GetString("Shahrokh_Havaejie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shahryear_Asgari {
            get {
                return ResourceManager.GetString("Shahryear_Asgari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sharzad_Golbabaie {
            get {
                return ResourceManager.GetString("Sharzad_Golbabaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shima_Sheybani {
            get {
                return ResourceManager.GetString("Shima_Sheybani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shima_Shirmohammadi {
            get {
                return ResourceManager.GetString("Shima_Shirmohammadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Shirin_Salajeghe {
            get {
                return ResourceManager.GetString("Shirin_Salajeghe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Siamak_Taheritabtabie {
            get {
                return ResourceManager.GetString("Siamak_Taheritabtabie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Simin_Azemati {
            get {
                return ResourceManager.GetString("Simin_Azemati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Siroos_Naemi {
            get {
                return ResourceManager.GetString("Siroos_Naemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sohrab_Negargar {
            get {
                return ResourceManager.GetString("Sohrab_Negargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Touraj_Babaie {
            get {
                return ResourceManager.GetString("Touraj_Babaie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vahidi {
            get {
                return ResourceManager.GetString("Vahidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vahid_Maroufie {
            get {
                return ResourceManager.GetString("Vahid_Maroufie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vahid_Sharbatdaran {
            get {
                return ResourceManager.GetString("Vahid_Sharbatdaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vali_Imantaleb {
            get {
                return ResourceManager.GetString("Vali_Imantaleb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Zahar_Fritos {
            get {
                return ResourceManager.GetString("Zahar_Fritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Zahra_Pourmehdi {
            get {
                return ResourceManager.GetString("Zahra_Pourmehdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ziaodin_Bahinaien {
            get {
                return ResourceManager.GetString("Ziaodin_Bahinaien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Ziya_Tutunchi_Ghorbani {
            get {
                return ResourceManager.GetString("Ziya_Tutunchi_Ghorbani", resourceCulture);
            }
        }
    }
}
